-- Relay-blind end-to-end media encryption.
--
-- streams.encrypted: per-stream opt-in. When 1, the broadcaster encrypts the
--   encoded media payload (AES-GCM) and viewers must decrypt with the content
--   key. The relay only ever forwards ciphertext.
-- broadcast_events.content_key: the per-broadcast symmetric content key
--   (base64url, 256-bit), generated by the Worker at go-live and handed to the
--   publisher (always) and to authorized viewers via /route. This is a SEPARATE
--   secret from the relay JWT-signing key and is NEVER sent to the relay.
ALTER TABLE streams ADD COLUMN encrypted INTEGER DEFAULT 0;
ALTER TABLE broadcast_events ADD COLUMN content_key TEXT;
